### ISSUE TITLE
SoundNode GetInputName now uses FText in 4.9

### ISSUE THREAD

**Issue by CalCof** [tomlooman/EpicSurvivalGameSeries#18]
To get the project working with UE 4.9 you need to alter the GetInputName method override in SoundNodeLocalPlayer to return FText. i.e. change the method definition to return FText and change the return statement to return an FText as well - something like:

FText USoundNodeLocalPlayer::GetInputPinName(int32 PinIndex) const
{
	//return (PinIndex == 0) ? TEXT("Local") : TEXT("Remote");
	return (PinIndex == 0) ? NSLOCTEXT("Survival", "InputPinName", "Local") : NSLOCTEXT("Survival", "InputPinName", "Remote");
}

Hope this helps, and thanks for such a great sample :-)

**Comment by tomlooman** [comment]
Thanks mate! I'll see if I can update to 4.9 soon. Any other issues you've ran into with conversion?
