### ISSUE TITLE
Update for UE4.13

### ISSUE THREAD

**Issue by calben** [tomlooman/EpicSurvivalGameSeries#25]
Project needs some minor updates for UE4.13

**Comment by CalCof** [comment]
Yep, it needs an extra include in SCharacater.cpp and a change inside SoundNodeLocalPlayer.cpp to alter the way the UAudioComponent is retrieved from the ActiveSound; it no longer has a get method (it stores and id and name instead).

**Comment by calben** [comment]
Was planning on quickly doing this yesterday, but time ran away from me.
Will probably be able to do it tonight :-)

**Comment by CalCof** [comment]
I did it yesterday, so I might as well submit a pull request; but its only actually two LOC anyway

**Comment by calben** [comment]
Surprisingly small!
I had assumed it would be a little more than that given the error messages.

**Comment by CalCof** [comment]
Yeah, they removed the UAudioComponent  ref and get method from FActiveSound in favour of storing the name and id. So you just need to change the way you get the ref. It actually stores the id and name of the owner too, but getting the actor by it's id seems to be dirtier than getting the audio component and just getting its owner. Anyhow, I submitted the pull request, well two actually as I had a bit of a fail with my browser windows.

**Comment by tomlooman** [comment]
Thanks gents! I just merged the PR for 4.13
