### ISSUE TITLE
when i generate file with .uc say not compile and rebuild from source.!!!!

### ISSUE THREAD

**Issue by mblogest** [tomlooman/EpicSurvivalGameSeries#30]

**Comment by jonny2027** [comment]
I am also getting the same issue on sections 1 and 2

**Comment by jonny2027** [comment]
I just took a copy of SurvivalGame.Target.cs and SurvivalGameEditor.Target.cs from the mast branch and replaced them in section 1 and 2 and it runs fine

**Comment by devilboy26** [comment]
Can you show me more about it ? i quite cant understand
