### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [tomlooman/EpicSurvivalGameSeries#34]
Thank you for making the code for this tutorial available! Could you please add an explicit LICENSE file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license):

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

Thanks!

**Comment by trdwll** [comment]
iirc Tom said it's 100% free to use commercially.

**Comment by mbrukman** [comment]
Thanks, @trdwll; unfortunately, the statement of "100% free to use commercially" is technically not an OSI-approved license. :-)

Would it be possible to choose a specific license, such as Apache, MIT, BSD, etc. and add a `LICENSE` file with that license to the repo? That clarifies all the license terms explicitly and makes lawyers happy.

**Comment by SRombauts** [comment]
Or use the Unreal Engine EULA

**Comment by trdwll** [comment]
@mbrukman Tom will have to add the license. I'm unable to go back to his and I conversation over a year ago about this. I do remember he said I'm able to sell this etc. Go shoot him an email or tweet him. http://www.tomlooman.com/contact/ 
He told me that it was made while he was contracted by Epic and that it's free like all of the content from Epic. So I'd say use the Unreal Engine EULA as @SRombauts had suggested. Just to clear the air, contact him.

**Comment by trdwll** [comment]
@mbrukman 
![license](https://imglnx.com/i/2bb6.png)

**Comment by mbrukman** [comment]
Thanks, @trdwll! Much appreciated.

**Comment by t31k3** [comment]
https://github.com/tomlooman/EpicSurvivalGameSeries/blob/master/LICENSE
