### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by ADMTec** [tomlooman/EpicSurvivalGameSeries#39]
Friend wanted to know if you could pass the project for summer 4.16.1?

**Comment by mariuz** [comment]
Seems that works fine with 4.16.1 , just project needs to  bump version 

https://github.com/tomlooman/EpicSurvivalGameSeries/pull/40

**Comment by wisien92** [comment]
@mariuz you dont get

> 2>C:\UE4\Survival\Source\SurvivalGame\Private\AI\BTTask_FindPatrolLocation.cpp(30): warning C4996: 'UNavigationSystem::GetRandomPointInNavigableRadius': This version of GetRandomPointInNavigableRadius is deprecated. Please use the new version Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.

when compiling?

**Comment by tomlooman** [comment]
FYI those are just warnings. the game functions fine without fixing those. I have fixed them in the upcoming release btw.
