### ISSUE TITLE
Will you make an open source shooter game too?

### ISSUE THREAD

**Issue by ColinSegieth** [tomlooman/EpicSurvivalGameSeries#41]
Is there any way that you could make a new project with a shooter AI? I mean cover system or something and AI with weapon? Your Survival Game Series is great, but a Shooter Game in third person would be awesome too. Please think about it and reply to this "issue" so I can see that you read it.

Greetings and all the best,
Colin

**Comment by ErwinALX** [comment]
I can help you

**Comment by ColinSegieth** [comment]
*Hey Erwin, very nice! I want to make a game like Rez Infinite, but I
thought about this and I`m not sure if this project is the right for my
game. It would be awesome if you could help me.*
*[CONTACT]: gerprogramminghub@gmail.com <gerprogramminghub@gmail.com>*

2017-08-11 6:32 GMT+02:00 Erwin Bustillo <notifications@github.com>:
