### ISSUE TITLE
Master branch may not be compiled to work with 4.18.1

### ISSUE THREAD

**Issue by WorksWellWithOthers** [tomlooman/EpicSurvivalGameSeries#42]
I was having difficulty getting the current master branch to work with 4.18.1.

"Could not be compiled. Try rebuilding from source manually."

The 4.17 branch works fine after copying it over and converting it to 4.18.1.

**Comment by MikeZteh69** [comment]
Having the same issue.

**Comment by tomlooman** [comment]
So what is the error when you try building from source manually? (eg. build from Visual Studio)

**Comment by MikeZteh69** [comment]
So it turns out that I was missing a VS SDK...that resolved it.

**Comment by devilboy26** [comment]
What is the unreal version?
