### ISSUE TITLE
Zombie AI

### ISSUE THREAD

**Issue by skeeta92** [tomlooman/EpicSurvivalGameSeries#51]
How do i setup the Zombie patrolling ? For some reason patrolling doesnt work..the only thing that works is when the zombie follows a player..

**Comment by wisien92** [comment]
Do you have BotWatpoint set up on map? There is an example map which is set up for that - ContainerCity.

**Comment by skeeta92** [comment]
That map doesnt work either...im using 4.19 im not sure if that makes a difference or not...

**Comment by paulnevada1983** [comment]
Use 4.18 - it works with it...

**Comment by tomlooman** [comment]
This was probably an obscure corruption of the blackboard asset that caused it to not work unless you loaded/opened the BB first in the editor. I occasionally noticed the patrolling not working and I now re-made the asset file and hopefully should not see this problem any longer.
