### ISSUE TITLE
Try rebuilding from source manually.

### ISSUE THREAD

**Issue by LucasAPDS** [tomlooman/EpicSurvivalGameSeries#56]
When opening the project in version 4.20.1 appears this message: SurvivalGame could not be compiled. Try rebuilding from source manually. What do I do? I'm new to this.

**Comment by LucasAPDS** [comment]
> Ao abrir o projeto na versão 4.20.1 aparece esta mensagem: SurvivalGame não pôde ser compilado. Tente recriar a partir da origem manualmente. O que eu faço? Eu sou novo nisso.

I found the solution :) : 
https://developer.microsoft.com/pt-br/windows/downloads/windows-10-sdk

**Comment by Jeff-HOU** [comment]
Thanks! This works for me!
