### ISSUE TITLE
Update Wiki links to use legacy site

### ISSUE THREAD

**Issue by caylorme** [tomlooman/EpicSurvivalGameSeries#64]
I've noticed the links to the wiki are all redirecting to the forum post about the community wiki being shut down. The old content is all hosted here: http://ue4community.wiki/legacy
If you want, we could update the links to reference that URL instead, might want to update the links within the wiki as well (if contributions are still welcome there), and also update your web page.

**Comment by tomlooman** [comment]
I am in the process of moving the section documentation to my own site. Section 1 was just completed. (https://www.tomlooman.com/survival-sample-game-for-ue4/section-one)

I'll update the readme once the transition is completed. I noticed the formatting on the new wiki is pretty broken too, unfortunately - especially the code bits didn't transport well.

**Comment by tomlooman** [comment]
I've updated a few of the URLs and used updated ue4community wiki for the rest until I get a chance to repost.
