### ISSUE TITLE
Which plugin version have you used?

### ISSUE THREAD

**Issue by hetul99** [tomlooman/EpicSurvivalGameSeries#71]
I am learning about hosting game on gamelift. For that, I require the plugin version that you have used in your latest update(i.e. 4.25). Can you provide that please as I didn't found that in your READ.md . I have to select from UE4.22.3, UE4.23.1 or UE4.24.3 as those are the only Gamelift plugins present in Gamelift's SDK
Thanks in Advance

**Comment by tomlooman** [comment]
I haven't used Gamelift for hosting. Any hosting testing has always been as "listen server" (where 1 player is the server) not a dedicated server.
