### ISSUE TITLE
EpicSurvivalGameSeries requested changes on the UE4 Engine/Editor that may create a dependency on my project even if I giveup on EpicSurvivalGameSeries?

### ISSUE THREAD

**Issue by t31k3** [tomlooman/EpicSurvivalGameSeries#84]
I mean: EpicSurvivalGameSeries recompiled UE4 engine and editor (https://github.com/tomlooman/EpicSurvivalGameSeries/issues/83)
I saw many new files at UE engine/editor path too.

I was creating a project based only on a compilation of vanilla UE4.26.2.

Does EpicSurvivalGameSeries requests changes on UE engine/editor that depend on EpicSurvivalGameSeries?

Or these requested changes are UE4 engine/editor options that were disabled?

And If I open my project on this newly compiled UE4 engine/editor, will it always require these changes to be applied/compiled even if I dont use these new features on my project? like in case I giveup on using EpicSurvivalGameSeries before trying to use it on my project, or by removing it from my project if possible?

These requested engine/editor changes are well supported or may be removed one day?

Are these requested engine/editor changes present on UE5? to when I finally migrate to it.

Obs.: My main target is android (32bits for now, until I move to UE5 one day).

**Comment by tomlooman** [comment]
The project doesn't change anything to the engine or editor. Compiling using the launcher version of the engine should work and only compile the project itself and make no changes to the engine in any case.

- Tom

**Comment by t31k3** [comment]
> The project doesn't change anything to the engine or editor. Compiling using the launcher version of the engine should work and only compile the project itself and make no changes to the engine in any case.
> 
>     * Tom

thx! btw, I forgot to say Im on linux, so there is no launcher here I think.
